all:maze scoreOfParentheses reverseSubString

maze:main_maze.cpp 
	g++ main_maze.cpp -o maze.out

scoreOfParentheses:main_scoreOfParentheses.cpp
	g++ main_scoreOfParentheses.cpp -o scoreOfParentheses.out

reverseSubString:main_reverseSubString.cpp
	g++ main_reverseSubString.cpp -o reverseSubString.out

