all:strstr strstrx numOccurrences anagram

strstr:main_strstr.cpp 
	g++ main_strstr.cpp -o strstr.out

strstrx:main_strstrx.cpp
	g++ main_strstrx.cpp -o strstrx.out

numOccurrences:main_numOccurrences.cpp
	g++ main_numOccurrences.cpp -o numOccurrences.out

anagram:main_anagram.cpp
	g++ main_anagram.cpp -o anagram.out
